export const GET_ALL_GROUPS = 'GET_ALL_GROUPS'
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const FETCH_GROUP_SUCCESS = 'FETCH_GROUP_SUCCESS'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
